"""empty message

Revision ID: 46900e4a69e7
Revises: 4de1da8cab2d
Create Date: 2025-06-03 16:25:45.848954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46900e4a69e7'
down_revision = '4de1da8cab2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
