"""Initial

Revision ID: 7f4865af8379
Revises: 
Create Date: 2025-06-03 15:55:12.045404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4865af8379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.alter_column('restaurante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('restaurante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
