"""Add status to Usuario

Revision ID: 899762145ad1
Revises: 431bc6838f84
Create Date: 2025-06-21 10:40:36.098558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899762145ad1'
down_revision = '431bc6838f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
