"""empty message

<<<<<<<< HEAD:migrations/versions/e06593884f4d_.py
Revision ID: e06593884f4d
Revises: 
Create Date: 2025-06-21 16:03:30.801742
========
Revision ID: 1308b88ed50f
Revises: 
Create Date: 2025-06-21 15:00:38.555748
>>>>>>>> 6f62104da870f0466f28a0c4ec9ea3b9ff98af16:migrations/versions/1308b88ed50f_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/e06593884f4d_.py
revision = 'e06593884f4d'
========
revision = '1308b88ed50f'
>>>>>>>> 6f62104da870f0466f28a0c4ec9ea3b9ff98af16:migrations/versions/1308b88ed50f_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=11), nullable=True),
    sa.Column('email_contacto', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('margen_objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje_min', sa.Float(), nullable=False),
    sa.Column('porcentaje_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'encargado', 'chef', name='roles'), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas_albaranes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('archivo_adjunto', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    op.drop_table('facturas_albaranes')
    op.drop_table('ventas')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('margen_objetivo')
    op.drop_table('restaurantes')
    # ### end Alembic commands ###
