"""empty message

Revision ID: ef0430dc3763
Revises: 5d9311cf2654
Create Date: 2025-06-12 15:40:15.495785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0430dc3763'
down_revision = '5d9311cf2654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
